import { execFileSync } from 'node:child_process';
import { readFile, writeFile } from 'node:fs/promises';
import vm from 'node:vm';

const CORE_COMMIT = 'eee6ce2ea9792263fa9420f980353cc108fc3123';
const repositoryRoot = new URL('../', import.meta.url);
const builderUrl = new URL('web-src/naknak-app.builder.html', repositoryRoot);
const caregiverUiUrl = new URL('web-src/caregiver-ui.jsx', repositoryRoot);
const caregiverCssUrl = new URL('web-src/caregiver-ui.css', repositoryRoot);
const outputUrl = new URL('naknak-app.html', repositoryRoot);

const builder = await readFile(builderUrl, 'utf8');
const caregiverUi = await readFile(caregiverUiUrl, 'utf8');
const caregiverCss = await readFile(caregiverCssUrl, 'utf8');

function extractTextBlock(id) {
  const pattern = new RegExp(
    `<script\\s+type=["']text/plain["']\\s+id=["']${id}["']>([\\s\\S]*?)<\\/script>`,
  );
  const match = builder.match(pattern);
  if (!match) throw new Error(`Missing build source block: ${id}`);
  return match[1];
}

const runnerMatch = builder.match(/<script>\s*(\(async function\(\)\{[\s\S]*?\}\)\(\);)\s*<\/script>\s*<\/body>/);
if (!runnerMatch) throw new Error('Missing NakNak build runner');

const core = execFileSync('git', ['show', `${CORE_COMMIT}:app.html`], {
  cwd: new URL('.', repositoryRoot),
  encoding: 'utf8',
  maxBuffer: 4 * 1024 * 1024,
});

let compiled = '';
const blocks = {
  'naknak-current-senior-home': extractTextBlock('naknak-current-senior-home'),
  'naknak-current-css': extractTextBlock('naknak-current-css'),
  'naknak-current-caregiver-ui': caregiverUi,
  'naknak-current-caregiver-css': caregiverCss,
};

const documentStub = {
  getElementById(id) {
    if (id === 'boot') return { innerHTML: '' };
    if (!(id in blocks)) throw new Error(`Unexpected document lookup during build: ${id}`);
    return { textContent: blocks[id] };
  },
  open() {},
  write(source) {
    compiled = source;
  },
  close() {},
};

const buildContext = {
  console,
  document: documentStub,
  navigator: {},
  fetch: async () => ({ ok: true, text: async () => core }),
};

await vm.runInNewContext(runnerMatch[1], buildContext, {
  filename: 'naknak-app.builder.html',
  timeout: 10_000,
});

// GitHub Pages cannot add response headers, but this harmless HTML-level
// fallback still prevents browsers from sending full paths/query strings as
// referrers when the static app links out. Header configuration remains the
// authoritative production control (documented in SECURITY.md).
const referrerMeta = '<meta name="referrer" content="strict-origin-when-cross-origin"/>\n';
if (!compiled.includes('name="referrer"')) {
  compiled = compiled.replace('</head>', `${referrerMeta}</head>`);
}
const pwaHead = '<meta name="theme-color" content="#C4301E"/>\n<link rel="manifest" href="./manifest.webmanifest"/>\n<link rel="apple-touch-icon" href="./Assets/apple-touch-icon.png"/>\n';
if (!compiled.includes('rel="manifest"')) {
  compiled = compiled.replace('</head>', `${pwaHead}</head>`);
}
const serviceWorkerRegistration = `<script>
if ('serviceWorker' in navigator && location.protocol !== 'file:') {
  window.addEventListener('load', () => navigator.serviceWorker.register('./naknak-sw.js').catch(() => undefined));
}
</script>\n`;
if (!compiled.includes("serviceWorker.register('./naknak-sw.js')")) {
  compiled = compiled.replace('</body>', `${serviceWorkerRegistration}</body>`);
}
compiled = compiled.replace(/[ \t]+$/gm, '').replace(/\n+$/g, '\n');

if (!compiled.includes('function SeniorHome')) throw new Error('Compiled app is missing SeniorHome');
if (compiled.includes('raw.githubusercontent.com/justineinacay/Naknak')) {
  throw new Error('Compiled app still contains a runtime core dependency');
}
if (compiled.includes('document.write(')) throw new Error('Compiled app still contains a wrapper loader');
if (compiled.includes('function EmergencyCallOverlay')) {
  throw new Error('Compiled app still contains the NakNak call-confirmation overlay');
}
if (!compiled.includes('Hindi pa aktibo ang remote SMS, automatic calling')) {
  throw new Error('Compiled app is missing the caregiver capability boundary');
}
if (!compiled.includes('className="nak-care-summary"')) {
  throw new Error('Compiled app is missing the current caregiver UI');
}
if (!compiled.includes('rel="manifest"') || !compiled.includes("serviceWorker.register('./naknak-sw.js')")) {
  throw new Error('Compiled app is missing PWA wiring');
}

const banner = `<!-- Generated by scripts/build-web.mjs from web-src/naknak-app.builder.html. -->\n`;
await writeFile(outputUrl, banner + compiled, 'utf8');
console.log(`Built ${new URL(outputUrl).pathname}`);
